<?php
use MageWorx\StoreLocator\Block\Search;

/** @var $block Search */
$defaultLocationId = $block->getLocationId();
?>
<div class="current_page_type" id="<?= $block->escapeHtmlAttr($block->getRequest()->getFullActionName()) ?>"></div>
<div class="mw-sl__search mw-sl__search--choose-location" id="mw-sl__search">
    <div class="mw-sl__search-select">
        <div class="mw-sl__search-select-content"><img src="<?= $block->escapeUrl(
                $block->getViewFileUrl('MageWorx_StoreLocator::images/svg/location.svg')
            ); ?>" alt="<?= $block->escapeHtml(__('Location icon')) ?>"/>
            <div class="mw-sl__search-select-location">
                <span id="mw_location_current_location_info"><?= $block->escapeHtml(
                        $block->getCurrentPlaceName()
                    ) ?></span>
                <div class="mw-sl__search-select-radius">
                    (<span id="mw_location_radius_info"> <?=
                        $block->escapeHtml($block->getDefaultRadiusValue()) ?></span> <?= $block->escapeHtml(
                        $block->getRadiusUnit() . ' ' . __('radius')
                    ) ?>)
                </div>
            </div>
        </div>
        <div class="mw-sl__search-select-actions">
            <button class="mw-sl__search-select-action mw-sl__search-select-action--edit-location" type="button">
                <?= $block->escapeHtml(__('Edit')) ?>
            </button>
            <button class="mw-sl__search-select-action mw-sl__search-select-action--reset-location" type="button"
                    onclick="resetSearch()">
                <?= $block->escapeHtml(__('Reset')) ?></button>
        </div>
    </div>
    <div class="mw-sl__search-form-content">
        <div class="block-search">
            <label for="mw-sl_search_text" class="sr-only">Find a store</label>
            <div class="input-group mb-3">
                <input name="search_text" class="form-control js-find-store" id="mw-sl_search_text" type="text" placeholder="Enter Location">
                <div class="input-group-append">
                    <button class="btn btn-primary" id="checkout-find-store" type="button" onclick="searchLocation('by_radius')">Find Store</button>
                </div>
            </div>
        </div>
        <div class="mw-sl__search__controls text-left">
            <?php if ($block->isSetToUseCurrentLocation()) : ?>
                <button type="button" class="btn btn-link btn-location py-0 px-2" id="searchCurrentLocation" onclick="getLocation()">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" aria-hidden="true" fill="currentColor"><path d="M.31 9.931h1.614a7.145 7.145 0 006.145 6.145v1.614a.311.311 0 00.31.31h1.242a.311.311 0 00.31-.31v-1.614a7.145 7.145 0 006.145-6.145h1.614a.311.311 0 00.31-.31V8.379a.311.311 0 00-.31-.31h-1.614a7.145 7.145 0 00-6.145-6.145V.31a.311.311 0 00-.31-.31H8.379a.311.311 0 00-.31.31v1.614a7.145 7.145 0 00-6.145 6.145H.31a.311.311 0 00-.31.31v1.242a.311.311 0 00.31.31zM9 3.724A5.276 5.276 0 113.724 9 5.276 5.276 0 019 3.724zm0 0"></path><path d="M11.482 9a2.483 2.483 0 11-2.483-2.483A2.483 2.483 0 0111.482 9zm0 0"></path></svg>
                    <span>Use my current location</span>
                </button>
                <div id="searchCurrentLocationStatus" class="alert alert-danger text-left mt-3" role="alert"></div>
            <?php endif; ?>
            <input type="hidden" name="radius" id="radius" value="<?= $block->escapeHtml($block->getDefaultRadiusValue()) ?>" />
            <input id="mw-sl__lat" name="autocomplete[lat]" type="hidden" />
            <input id="mw-sl__lng" name="autocomplete[lng]" type="hidden" />
            <input class="field" name="autocomplete[small_city]" id="mw_sublocality_level_1" type="hidden" />
            <input class="field" name="autocomplete[city]" id="mw_locality" type="hidden" />
            <input class="field" name="autocomplete[region]" id="mw_administrative_area_level_1" type="hidden" />
            <input class="field" name="autocomplete[postcode]" id="mw_postal_code" type="hidden" />
            <input class="field" name="autocomplete[country_id]" id="mw_country" type="hidden" />
        </div>
    </div>
</div>
<div id="HG_dummyData" class="d-none">
</div>
<script type="text/javascript">
    // TODO: refactor this
    var map;
    var getLocationButton = document.getElementById("searchCurrentLocation");
    var getLocationButtonStatus = document.getElementById("searchCurrentLocationStatus");
    var defaultAllStoresBlockHtml;
    var defaultLocationListBlockHtml;

    var queryString = window.location.search;
    var urlParams = new URLSearchParams(queryString);
    if (urlParams.get('search_text')) {
        document.getElementById('mw-sl_search_text').value = urlParams.get('search_text');
        setTimeout(function () {
            searchLocation('by_radius');
        }, 1000);
    }

    if (getLocationButtonStatus) {
        var getLocationButtonText = getLocationButtonStatus.innerHTML;
    } else {
        var getLocationButtonText = '';
    }

    function searchLocation(type) {
        jQuery('#mw_postal_code').val(jQuery('#mw-sl_search_text').val());
        var data = getData();
        var currentPage = jQuery('.current_page_type').attr('id');
        var currentProduct = jQuery('.current_product').attr('id');
        jQuery.ajax({
            url: '<?= $block->escapeUrl(
                    $block->getBaseUrl()
                );?>store_locator/location/searchLocations?_=' + new Date().getTime() + '&type=' + type
                + '&current_page=' + currentPage + '&current_products=' + currentProduct,
            type: 'POST',
            isAjax: true,
            dataType: 'html',
            showLoader: true,
            data: data,
            success: function (xhr, status, errorThrown) {
                var result = xhr.split('||');
                jQuery('#mw-all-stores').html(result[0]);
                jQuery('#HG_dummyData').html(result[0]);


                if (result[1] !== undefined) {
                    jQuery('#mw-all-stores-filters').html(result[1]);
                    jQuery('.mw-sl__stores__list__item').show();
                    displayData();

                }
                if (place !== undefined && place.geometry !== undefined && map !== undefined) {
                    map.setCenter(place.geometry.location);
                    map.fitBounds(place.geometry.viewport);
                }

                hideSearchForm();
            },
            error: function (xhr, status, errorThrown) {
                console.log('There was an error loading stores\' data.');
                console.log(errorThrown);
            }
        });
    }
    function displayData(){
        var loopCounter=0;
        var storeHtml='';
        jQuery('#HG_dummyData ul#store_all_pages li').each(function(i) {
            if (loopCounter<5) {
                storeHtml = storeHtml+jQuery(this).html();
            }
            loopCounter++;
        });
        //jQuery("#storeSearch_checkout_location").html('');
        jQuery("#HG_dummyData").html('');
        if(storeHtml=='')
            jQuery(".pick_div .pickup_data_stores").html('<p><b>No stores found</b></p>');
        else
            jQuery(".pick_div .pickup_data_stores").html(storeHtml);
        jQuery("#storeSearch_checkout_location").html('');
    }

    function hideSearchForm() {
        jQuery('.mw-sl__stores').css('height', '530px');
        jQuery('.mw-sl__content--map-right .mw-sl__stores').css('height', '600px');
    }

    function getData() {
        var formValue = function (name, value) {
            this.name = name;
            this.value = value;
        };

        var inputValues = jQuery('#mw-sl__search :input').map(function () {
            var type = jQuery(this).prop("type");

            if ((type === "checkbox" || type === "radio") && this.checked) {
                return new formValue(this.name, jQuery(this).val());
            } else if (type !== "button" && type !== "submit") {
                return new formValue(this.name, jQuery(this).val());
            }
        });

        var radius = jQuery('#radius-select').val();
        if (radius !== "0") {
            jQuery('.mw-sl__search-select-radius').show();
            jQuery('#mw_location_radius_info').text(radius);
        } else {
            jQuery('.mw-sl__search-select-radius').hide();
        }

        return inputValues;
    }

    function getLocation() {
        jQuery('body').loader('show');
        for (var component in componentForm) {
            document.getElementById('mw_' + component).value = '';
        }

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(
                showPosition,
                locationFail,
                {
                    maximumAge: 50000,
                    timeout: 10000,
                    enableHighAccuracy: true
                });
        } else {
            getLocationButton.innerHTML = "<?= $block->escapeHtml(
                __('Geolocation is not supported by this browser.')
            )?>";
        }
    }

    function showPosition(position) {
        var geocoder;
        geocoder = new google.maps.Geocoder();
        var coordinates = {lat: position.coords.latitude, lng: position.coords.longitude};
        var currentPositionName = '';
        place = undefined;
        geocoder.geocode({'location': coordinates}, function (results, status) {
            if (status === 'OK' && results[0]['formatted_address'] !== undefined) {
                currentPositionName = results[0]['formatted_address'];
            } else {
                currentPositionName = "<?= $block->escapeHtml(
                    __('My location')
                )?>";
            }

            jQuery("#sl__stores__current_place").text(currentPositionName);
            jQuery("#mw_location_current_location_info").text(currentPositionName);
            var address = currentPositionName.split(", ");
            var preparedName = address[address.length - 1];
            if (address[address.length - 2] !== undefined) {
                preparedName = address[address.length - 2] + ', ' + preparedName;
            }
            if (
                document.getElementById('mw-sl_search_text2') &&
                document.getElementById('mw-sl_search_text2').value
            ) {
                jQuery("#mw-sl_search_text2").val(preparedName);
            } else {
                jQuery("#mw-sl_search_text").val(preparedName);
            }
        });

        jQuery("#mw-sl__lat").val(position.coords.latitude);
        jQuery("#mw-sl__lng").val(position.coords.longitude);
        jQuery("#searchCurrentLocation").addClass('mw-sl__search__current-location__loaded');
        jQuery('body').loader('hide');
    }

    function tryAPIGeolocation(apiKey) {
        jQuery.post("https://www.googleapis.com/geolocation/v1/geolocate?key=<?=
            $block->escapeHtml($block->getApiKey())?>", function (success) {
            showPosition({coords: {latitude: success.location.lat, longitude: success.location.lng}});
        })
            .fail(function (err) {
                console.log(
                    "<?= $block->escapeHtml(
                        __('API Geolocation error.')
                    )?>" + err.responseJSON.error.message);
                getLocationButtonStatus.innerHTML = getLocationButtonText + "<?= $block->escapeHtml(
                    __('Could not load geo position.')
                )?>";
            });
    }

    function locationFail(error, apiKey) {
        switch (error.code) {
            case error.TIMEOUT:
                console.log(
                    "<?= $block->escapeHtml(
                        __('Browser geolocation timeout error. ')
                    )?>" + error.message);
                getLocationButtonStatus.innerHTML = getLocationButtonText + "<?= $block->escapeHtml(
                    __('Could not load geo position. ')
                )?>";
                break;
            case error.PERMISSION_DENIED:
                tryAPIGeolocation(apiKey);
                break;
            case error.POSITION_UNAVAILABLE:
            default:
                console.log(
                    "<?= $block->escapeHtml(
                        __('Geo position unavailable.')
                    )?>" + error.message);
                getLocationButtonStatus.innerHTML = getLocationButtonText + "<?= $block->escapeHtml(
                    __('Could not load geo position from browser.')
                )?>";
                break;
        }
        jQuery('body').loader('hide');
    };

    function resetSearch() {
        var defaultRadius = '<?= $block->escapeHtml($block->getDefaultRadiusValue()) ?>';
        var defaultPlace = '<?= $block->escapeHtml($block->getCurrentPlaceName()) ?>';

        // jQuery('.mw-sl__search').addClass('mw-sl__search--choose-location');
        jQuery('.mw-sl__stores').css('height', '330px');
        jQuery('.mw-sl__content--map-right .mw-sl__stores').css('height', '400px');

        jQuery('.mw-sl__search-select-radius').show();
        jQuery('#mw_location_radius_info').text(defaultRadius);
        jQuery('#radius-select').val(defaultRadius);

        jQuery('#mw_location_current_location_info').text(defaultPlace);
        jQuery('#mw-sl_search_text').val(defaultPlace);
        jQuery('.mw-sl__stores__current').text(defaultPlace);

        jQuery('#mw-all-stores').html(defaultAllStoresBlockHtml);
        jQuery('#mw-sl__stores__list_block').html(defaultLocationListBlockHtml);
        jQuery("#searchCurrentLocation").removeClass('mw-sl__search__current-location__loaded');

        if (map !== undefined) {
            map.setCenter(center);
            map.setZoom(zoom);
        }
    }

    require([
        "jquery"
    ], function ($) {
        jQuery(document).ready(function () {
            let locationId = getCookie('mageworx_location_id');
            const defaultLocationId = <?=$defaultLocationId?>;

            if (!locationId && defaultLocationId) {
                document.cookie = `mageworx_location_id=${defaultLocationId}; expires=604800; path=/`;
                locationId = defaultLocationId;
            }
            if (locationId) {
                let url = '<?php echo $block->escapeUrl($block->getUrl('highgrove_store_locator/location/selected')); ?>'+'location/'+locationId;

                $.ajax({
                    url: url,
                    type: 'GET',
                    isAjax: true,
                    dataType: 'html',
                    showLoader: true,
                    success: function (xhr, status, errorThrown) {
                        let defaultLocationListBlock = $("#storeSearch_checkout_location");
                        defaultLocationListBlock.html(xhr);
                    }
                });
            }
        });

        jQuery('#mw-sl_search_text').bind("enterKey", function (e) {
            setTimeout(function () {
                searchLocation('by_radius');
            }, 500);
        });

        jQuery('#mw-sl_search_text').keyup(function (e) {
            if (e.keyCode == 13) {
                jQuery(this).trigger("enterKey");
            }
        });
    });

    function getCookie(cname) {
        var name = cname + "=";
        var ca = document.cookie.split(';');
        for(var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }
        }
        return "";
    }

    function initialize()
    {
        initAutocomplete({country: ['au']});
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<?= $block->escapeHtml($block->getApiKey()); ?>&callback=initialize&libraries=places&sensor=true&v=3" defer></script>
