<?php
/** @var \Highgrove\StoreLocator\ViewModel\Location $viewModel */
//$viewModel = $block->getViewModel();
//$location = $viewModel->getCurrentLocation();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$findStore = $objectManager->get('\Highgrove\StoreLocator\Block\Catalog\Product\FindAStore');
$currentCookieStore = $findStore->getCookieStore();
$blockObj= $block->getLayout()->createBlock('\Highgrove\StoreLocator\Block\LocationsList');
?>

<div class="top-bar top-left mr-auto">
    <button type="button" class="btn btn-link btn-location p-0" id="setLocationToggler" data-mage-init='{"locations-modal": {"target": "#locationPopup", "dataUrl": "<?= $block->getBaseUrl(); ?>"}}'>
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 446.381 446.381"><circle cx="223.19" cy="223.19" r="50.998"/><path d="M441.381 193.19h-39.666C389.014 117.362 329.018 57.367 253.19 44.666V5a5 5 0 00-5-5h-50a5 5 0 00-5 5v39.666C117.362 57.367 57.367 117.362 44.666 193.19H5a5 5 0 00-5 5v50a5 5 0 005 5h39.666c12.701 75.828 72.696 135.824 148.524 148.525v39.666c0 2.76 2.239 5 5 5h50a5 5 0 005-5v-39.666c75.828-12.701 135.824-72.697 148.525-148.525h39.666a5 5 0 005-5v-50a5 5 0 00-5-5zM223.19 354.214c-72.247 0-131.024-58.776-131.024-131.024 0-72.247 58.777-131.024 131.024-131.024 72.248 0 131.025 58.777 131.025 131.024 0 72.248-58.777 131.024-131.025 131.024z"/></svg>
        <?php /*if ($currentCookieStore): ?>
            <span class="set-my-locaton">Your store: <?php echo $currentCookieStore->getName(); ?>, <?php echo $currentCookieStore->getPostcode(); ?></span>
        <?php else: */?>
            <span class="set-my-locaton">Set my location</span>
        <?php //endif; ?>
    </button>
</div>

<script type="text/javascript">
require(["jquery"], function ($) {
    $(document).ready(function () {
       var cookieValue = getCookie('mageworx_location_id');
		if(cookieValue)
		{
			$('.set-my-locaton').html('...Loading ');
			$.ajax({
                    url: '<?php echo $blockObj->getAjaxUrl()?>',
                    type: 'POST',
                    isAjax: true,
                    showLoader: true,
                    data:'loc_id='+cookieValue,
                    success: function (xhr, status, errorThrown) {
                     if(xhr)
                      {
                        $('.set-my-locaton').html('Your store: '+xhr.name+', '+xhr.postcode);
                        $('.set-my-locaton-mob').html(xhr.name+', '+xhr.postcode);
                      }
                    },
                    error: function (xhr, status, errorThrown) {
                      
                    }
              });
		}
    });
})
function getCookie(cname) {
  var name = cname + "=";
  var ca = document.cookie.split(';');
  for(var i = 0; i < ca.length; i++) {
      var c = ca[i];
      while (c.charAt(0) == ' ') {
          c = c.substring(1);
      }
      if (c.indexOf(name) == 0) {
          return c.substring(name.length, c.length);
      }
  }
  return "";
}
</script>